# Build
custom_build(
    # Name of the container image
    ref = 'order',
    command = 'mvnw spring-boot:build-image -Dmodule.image.name=%EXPECTED_REF%',
    # Files to watch that trigger a new build
    deps = ['pom.xml', 'src']
)

# Deploy
k8s_yaml(['k8s/deployment.yml', 'k8s/service.yml'])

# Manage
k8s_resource('order', port_forwards=['9001'])