include('C:/msc/Research/microroutenet/order/Tiltfile')
include('C:/msc/Research/microroutenet/payment/Tiltfile')
include('C:/msc/Research/microroutenet/warehouse/Tiltfile')

update_settings(max_parallel_updates=1)
