server:
  port: 8082
spring:
  application:
    name: warehouse-internal
  datasource:
    url: jdbc:postgresql://localhost:5432/microroutenet
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true