spring:
  application:
    name: payment
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      
management:
  endpoints:
    web:
      exposure:
        include: refresh

microroutenet-configs:
  local-communication:
    port: 8083
  inter-communication:
    - name: payment-completed-order
      plugin: rest
    - name: payment-completed-warehouse
      plugin: kafka
  rest:
    info: 
      - name: payment-completed-order
        method: GET
        api: http://localhost:8081/order/{id}/{status}
      - name: payment-completed-warehouse
        api: http://localhost:8082/product/reserve/{id}
        method: GET
  plugins:
    kafka-class-name: org.microroutenet.KafkaPlugin
    kafka-payment-completed-warehouse:
      topic: warehouse-topic
          



server:
  port: 9093